### ISSUE TITLE
Wasn't able to find node on my system

### ISSUE THREAD

**Issue by codeincontext** [sindresorhus/alfred-emoj#1]
Hi, thanks for this. Super cool.

I had to tweak some things to get this to work. Don't know if it's my environment but could be useful to know. It wasn't working, I turned on the debug output and got this:

```
[2016-06-26 21:21:33][ERROR: input.scriptfilter] Code 127: bash: no job control in this shell
/Users/adz/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/F7C3D82A-57F6-4032-92FF-E179415ACB0D: line 2: node: command not found
```

The fist line seems to be ignorable. The second not so much. I changed the script to point to my node (`which node`) which fixed it

```
/usr/local/bin/node index.js "$1"
```

Thanks!

**Comment by sindresorhus** [comment]
What output do you get if you add in `foo=$($(echo $SHELL) -ic 'echo $PATH');echo $foo` in the workflow?

**Comment by codeincontext** [comment]
`/usr/bin:/bin:/usr/sbin:/sbin:/Users/adz/.fzf/bin`

**Comment by sindresorhus** [comment]
Hmm, weird.

Can you try replacing the script with:

``` sh
PATH=$($(echo $SHELL) -ic 'echo $PATH'):/usr/local/bin:$PATH
node index.js "$1"
```

## 

What's the output when running these commands in your Terminal (not in the Alfred workflow):
- `echo $SHELL`
- `bash --version`
- `zsh --version`
- `echo $PATH`

**Comment by codeincontext** [comment]
That works

Don't think it should matter but FWIW I normally use Fish

``` bash
Adams-MBP-4:~ adz$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
Adams-MBP-4:~ adz$ zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
Adams-MBP-4:~ adz$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by sindresorhus** [comment]
So `Fish` is your default shell? Do you know the `Fish` equivalent of `echo $($(echo $SHELL) -ic 'echo $PATH')`? (That snippets spawns your default shell interactively and get's your $PATH.) I would guess it doesn't work because you default shell is Fish and it tries to spawn Fish with unsupported flags and syntax.

## 

0.1.1 is out with the fix btw. http://www.packal.org/workflow/emoj

**Comment by codeincontext** [comment]
I should have been clearer; bash is still my default shell for compatibility reasons, but I don't use it often and it may not be configured in a typical way. I think Alfred hard codes `/bin/bash` anyway

And cool, thanks sir

**Comment by sindresorhus** [comment]
Ok, cool :)

Last favor. Could you replace it with this and see if it still works?

``` sh
eval $(/usr/libexec/path_helper -s)
export PATH=/usr/local/bin:$($(echo $SHELL) -ic 'echo $PATH'):$PATH

node index.js "$1"
```

Just want to ensure I don't break it again.

**Comment by codeincontext** [comment]
Yep, still works ✔✅🔜👌➡👍☑😌🔄🙌

**Comment by sindresorhus** [comment]
👍👌😃😄😀👏😎😊😁

**Comment by CWSpear** [comment]
@sindresorhus does it solve anything by using something like [`enclose.js`](https://github.com/igorklopov/enclose)? to package your module as a binary? I was able to package the script from this repo. It was about 15 MB. Could this be a workaround cuz then we wouldn't _need_ to know `PATH`? And since you're only targeting Macs, it's okay if it's only compiled for Macs.

**Comment by sindresorhus** [comment]
@CWSpear Last resort maybe, but hope it doesn't get to that.

**Comment by CWSpear** [comment]
Why is that a last resort?

**Comment by sindresorhus** [comment]
Because it's 15 MB, and while I don't mind that, people will complain and call it a waste of space. I also think I can fix it without, so at least gonna try. Packaging as a binary surely come with its own quirk and problems too.

**Comment by sindresorhus** [comment]
But most importantly, users don't like installing random binaries and not seeing what kind of source they're running.

**Comment by CWSpear** [comment]
The source is on GitHub, and people are welcome to download and build themselves (or at least if you trust the developer, just check the checksum). I think it's a valid concern, but I don't know if it's really something that is your responsibility.

I mean, there are lots of tools/languages/other places that package binaries and stuff (having dabbled in Go, that's all you do!). I can't speak for everyone, but I think the advantages of "just works" and not having to deal with "works in my environment but not yours" greatly outweighs that.

Anyway, it's your project, and I know you deal with a ton of projects and issues. I just wanted to offer the suggestion hoping it might help. I definitely won't be offended if you don't take the suggestion =)

Thanks for all your awesome work in the Node et al community!
