### ISSUE TITLE
Slow Results

### ISSUE THREAD

**Issue by AlecRust** [sindresorhus/alfred-emoj#11]
Any ideas on why this Workflow takes so long to return results? For any given query I'm sat waiting for many second:

![screencast](http://i.imgur.com/6ontjJP.gif)

The results also don't seem to cache, in the above screencast I make the same search twice.

**Comment by sindresorhus** [comment]
Either the API servers are overloaded (out of my control) or you're on a slow network. It's fast for me.

I guess we could cache the results for a week. I just didn't see the point personally as I never search for the same thing twice.

**Comment by AlecRust** [comment]
Interesting to know it's fast for you, has always been slow for me on different connections, and my main connection is very fast. Am based in London.

Fair enough regarding the caching, seems this is more an issue with the Dango API than this Workflow.

**Comment by SamVerschueren** [comment]
@sindresorhus this might have something to do with alfred-notifier trying to find an update. 

@AlecRust can you remove the package and reinstall it? Does it make any difference?

**Comment by AlecRust** [comment]
Deleting from Alfred and re-installing with `npm install --global alfred-emoj` seems to make no difference.

**Comment by revelt** [comment]
I came here because it's slow for me too. It was OK up until roughly a month ago, then it started to get too slow. I'm using [rocket for Mac](http://matthewpalmer.net/rocket/) as a backup currently.

**Comment by harrisrobin** [comment]
It's not working at all for me as of today. *Insert a "hmm" emoj*

**Comment by joech4n** [comment]
+1. Also not working for me...

**Comment by SamVerschueren** [comment]
See #15. Looks like the API is paid as of now.

**Comment by harrisrobin** [comment]
@AlecRust off topic but what's your alfred theme? :D

**Comment by AlecRust** [comment]
@harrisrobin just one of the default themes "Alfred macOS Dark".

![screenshot](https://i.imgur.com/0sRRwsC.png)

**Comment by joech4n** [comment]
For those looking for another workflow: 

- built-in Alfred snippets with [this Emoji Pack](http://joelcalifa.com/blog/alfred-emoji-snippet-pack/)
- https://github.com/jsumners/alfred-emoji, though it's not [deep learning powered with Dango's API](https://getdango.com/emoji-and-deep-learning/)...
- [Another alternative (I'm using this now as it autoupdates from unicode)](https://github.com/jeeftor/EmojiTaco)

Maybe someone can build a workflow with the [Emojidex API](http://developer.emojidex.com/#the-emojidex-service) :)

**Comment by sindresorhus** [comment]
Closing as there's nothing I can do.
