### ISSUE TITLE
Certificate Expired 😢

### ISSUE THREAD

**Issue by FrancesCoronel** [sindresorhus/alfred-emoj#13]
## I'm getting the following certification expiration error after initially installing the workflow and testing it out in Alfred.

Any thoughts on how I should go about fixing it? 

I tried looking at the line where it errored but it wasn't too helpful.

<img width="634" alt="screenshot 2017-07-15 20 01 36" src="https://user-images.githubusercontent.com/4284691/28244257-75d8b0a0-699a-11e7-976a-38bbd7cdb4b8.png">

> Error message copied below

```
emoj smileRequestError: certificate has expired 
   at ClientRequest.req.once.err (/usr/local/lib/node_modules/alfred-emoj/node_modules/got/index.js:73:21)
```

<img width="1527" alt="screenshot 2017-07-15 20 01 44" src="https://user-images.githubusercontent.com/4284691/28244258-75d907e4-699a-11e7-8b6e-4c5d8e1418d5.png">

**Comment by sindresorhus** [comment]
Seems like it was just a temporary issue. It works now.

**Comment by mixn** [comment]
I’ve started randomly experiencing this, too. Any idea what’s causing it?

Great, life-saving tool overall (as many others you’ve made). Thank you, @sindresorhus. ❤️
