### ISSUE TITLE
question: update emoji dictionary

### ISSUE THREAD

**Issue by steveoh** [sindresorhus/alfred-emoj#14]
it looks like this workflow doesn't really have control over how emoji's are discovered but I figured I would ask since ¯\_(ツ)_/¯. 

I can't get [this emoji](http://emojipedia.org/hand-with-index-and-middle-fingers-crossed/) 🤞 with the app. fingers, cross, fingers crossed, hand with index and middle fingers crossed, etc.

Can you tell me if there is a route to report and solve these types of issues upstream?

**Comment by sindresorhus** [comment]
We don't control the results. It's a third-party service. We could maybe mix those results with an offline database of up-to-date emojis. Open an issue on https://github.com/sindresorhus/emoj and we can discuss it there.
