### ISSUE TITLE
 A .alfredworkflow download within the releases

### ISSUE THREAD

**Issue by patilswapnilv** [sindresorhus/alfred-emoj#19]
Hey @sindresorhus, 

Thanks for building a useful tool. We all love emoji's isn't it :-) 

The npm install did not work for me. While I am looking into why it did not work, I wonder how nice it would be to have a alfredworkflow download file.

Is this something that is on your agenda for the next releases?

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in doing the extra work of providing alfredworkflow files. Open an issue on https://github.com/SamVerschueren/alfred-link about your problems and we'll try to fix it.
