### ISSUE TITLE
TypeError when there are no results

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/alfred-emoj#2]
I'm pretty sure that this is because the API isn't returning results for the search query, which leads to there not being an array to `map`.

![TypeError](https://cloud.githubusercontent.com/assets/737065/16381839/51f5b768-3c4c-11e6-9d47-0306e35fca94.png)

**Comment by sindresorhus** [comment]
Weird. I've never been able to get it to not return anything. `emoj whatever` works for me. Do you have anything reproducible I could try?

**Comment by paulmolluzzo** [comment]
I can't actually get anything to work. Do I need to install anything other than the workflow? I have Alfred v3.0.2

**Comment by sindresorhus** [comment]
If you press Enter on the error item it will copy the stack. Can you share?

**Comment by paulmolluzzo** [comment]
It's not copying when I press error or click... :/

**Comment by paulmolluzzo** [comment]
Hmm, your `alfred-npm` workflow isn't working either. I've refreshed Alfred. I may need to do a machine reboot but can't do it at the moment...

**Comment by paulmolluzzo** [comment]
OK, did a reboot and a fresh install and I still have the issue. I opened the Alfred debugger and get this error:

```
[2016-06-27 21:55:31][STDERR: input.scriptfilter] bash: cannot set terminal process group (2697): Inappropriate ioctl for device
bash: no job control in this shell
stty: stdin isn't a terminal
```

I opened the actual directory for the workflow and manually replicated the command `node index.js [test phrase]` and that is returning data.

I am running OSX 10.10.5

**Comment by paulmolluzzo** [comment]
OK, I found a working solution, but it could be unique to my machine:

I changed out the script filter to be as follows:

``` bash
export PATH=/usr/local/bin/:$PATH

node index.js "$1"
```

This is the first solution I found in this old forum post: http://www.alfredforum.com/topic/2436-path-in-alfred-workflows/

e: If I can help debug further let me know. I didn't close it just in case you want to work out a solution first.

**Comment by sindresorhus** [comment]
@paulmolluzzo Looks similar to https://github.com/sindresorhus/alfred-npms/issues/1

**Comment by paulmolluzzo** [comment]
It does, and that thread almost comes to the same solution of using `export PATH=/usr/local/bin/:$PATH` but they had a bunch of stuff to source their `bashrc`/`profile`, which might have caused that strange output.

I'm going to ask if this solution solves it for them too.

**Comment by sindresorhus** [comment]
> I'm going to ask if this solution solves it for them too.

It doesn't.

**Comment by paulmolluzzo** [comment]
They didn't match mine exactly. They missed a trailing `/` and also sourced other stuff first.

**Comment by sindresorhus** [comment]
Can you try out the latest version? http://www.packal.org/workflow/emoj

**Comment by paulmolluzzo** [comment]
This is working great right out of the box! Thanks!
