### ISSUE TITLE
Workflow isn't listed in Alfred after install

### ISSUE THREAD

**Issue by maltsev** [sindresorhus/alfred-emoj#21]
Hi Sindre,

I just tried to install your workflow:
```
npm install --global alfred-emoj

> alfred-emoj@2.0.0 postinstall /usr/local/lib/node_modules/alfred-emoj
> alfy-init

+ alfred-emoj@2.0.0
added 200 packages from 69 contributors in 7.532s
```

I got no errors, but the workflow isn't listed in Alfred. I guess this might be related to the latest major Alfred upgrade.

Here is my environment:
- Alfred 4.0.2 [1088]
- Node.js v12.3.1
- npm 6.9.0

Let me know if you need more information from me!

**Comment by sindresorhus** [comment]
Try reinstalling Alfred 4 should be supported now. If you still have problems, open an issue on https://github.com/SamVerschueren/alfred-link
