### ISSUE TITLE
Cannot find emoji:  ''RequestError: getaddrinfo ENOTFOUND emoji.getdango.com"

### ISSUE THREAD

**Issue by nicokosi** [sindresorhus/alfred-emoj#26]
![image](https://user-images.githubusercontent.com/3862051/91636969-0d792280-ea05-11ea-83ae-70a66a90e163.png)

Error is:
```
RequestError: getaddrinfo ENOTFOUND emoji.getdango.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/alfred-emoj/node_modules/got/index.js:182:22)

Emoj 2.0.0
Alfred 3.8.6
darwin x64 19.6.0
```

https://emoji.getdango.com seems to be down.

**Comment by sindresorhus** [comment]
Please check closed issues (you should always do that). This happens once in a while. Out of our control.

**Comment by nicokosi** [comment]
I could not find similar issue. Issue #13 is a bit similar but had visibly a different cause.
Anyway, I understand it is related to [getdango.com](getdango.com) which is not under your control.

**Comment by nicokosi** [comment]
This workaround worked for me: https://github.com/sindresorhus/alfred-emoj/issues/27#issuecomment-703635432.
Thank you @Bergrebell. 👍
