### ISSUE TITLE
Is it possible to add support to a theme I use to highlight the results better?

### ISSUE THREAD

**Issue by nikivdev** [sindresorhus/alfred-emoj#4]
I currently use [this great theme](https://www.alfredapp.com/extras/theme/54WVQdqKo6/) and with it, when you try and choose an emoji and scroll through them you don't know which one is picked as it does not highlight them in any way : 

![2016-06-30 at 17 17](https://cloud.githubusercontent.com/assets/6391776/16493667/9a3cb78c-3ee6-11e6-86c3-7cee061f8555.png)

There is no way to see what is being highlighted. Is there some way to change that as I would really like to use this workflow as it seems really fun.

**Comment by sindresorhus** [comment]
That's a bug in the theme you're using. Works fine with the default theme.

<img width="593" alt="screen shot 2016-06-30 at 21 52 25" src="https://cloud.githubusercontent.com/assets/170270/16502109/01159778-3f0d-11e6-8c92-790415287b43.png">
