### ISSUE TITLE
Error installing on OSX

### ISSUE THREAD

**Issue by xhain** [sindresorhus/alfred-emoj#8]
Hey there!
I'd love to try this out, but I get this:

```
MacBook:~ max$ sudo npm install --global alfred-emoj
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
\
> alfred-emoj@0.2.0 postinstall /usr/local/lib/node_modules/alfred-emoj
> alfy-init

{ [Error: Command failed: alfred-link
[Error: Alfred preferences not found at location /Users/max/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist]
]
  code: 1,
  killed: false,
  stdout: '',
  stderr: '[Error: Alfred preferences not found at location /Users/max/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist]\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link' }
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "alfred-emoj"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! alfred-emoj@0.2.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-emoj@0.2.0 postinstall script 'alfy-init'.
npm ERR! This is most likely a problem with the alfred-emoj package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     alfy-init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alfred-emoj
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls alfred-emoj
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/max/npm-debug.log
```

Keep up the great work!
Max

**Comment by sindresorhus** [comment]
You have Alfred 3, right? Not Alfred 2.

**Comment by xhain** [comment]
Yes.

Am 21.10.2016 04:46 schrieb "Sindre Sorhus" notifications@github.com:

**Comment by sindresorhus** [comment]
> [Error: Alfred preferences not found at location /Users/max/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist]

Where are your Alfred preferences stored?

**Comment by xhain** [comment]
In a dropbox folder via the Alfred backup function.
Done when migrating from Alfred 2 to 3.

**Comment by SamVerschueren** [comment]
That's odd. Care to take a screenshot of your `Advanced` tab in the Alfred preferences app? More specifically, the `Syncing` setting. It should be picked up automatically. Maybe it has a different format because you migrated from Alfred 2 to 3...

**Comment by xhain** [comment]
Sure, anything that helps!
I attached a screenshot of the Syncing Setting (~/Dropbox/Backup/Alfred 2).
Does this help, old do you need the whole tab?

PS: It's probably because it's in "Dropbox/Backup/Alfred 2/" and not "Dropbox/Alfred 2/", right?)

**Comment by SamVerschueren** [comment]
Screenshots doesn't seem to work through mail :).

I read your initial post again. It's not that it can't find your syncing folder, it's because it can't find the Alfred preferences in the first place. Could you check if you have something Alfred like in this directory?

> /Users/max/Library/Preferences

It should be 

> /Users/max/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist

But maybe something goes different when you upgrade from Alfred 2 to 3.

Are you 100% sure you have Alfred 3 installed? Just to make sure we're not hunting for something that shouldn't work in the first place.

**Comment by xhain** [comment]
What I found in /Users/max/Library/Preferences:

com.runningwithcrayons.Alfred-2.plist
com.runningwithcrayons.Alfred-3.plist
com.runningwithcrayons.Alfred-Preferences-3.plist
com.runningwithcrayons.Alfred-Preferences.plist

I can confirm that I'm using the current, legally bought, version of Alfred 3:

Alfred 3.1.1
Build 736, Saturday 17th September 2016

Thanks again,
Max

**Comment by SamVerschueren** [comment]
Oh, could it be because you are using `sudo`? Never ever install using sudo! Just run `npm install alfred-emoj`.

**Comment by xhain** [comment]
I think using sudo was a desperate attempt. I tried it earlier without sudo and it didn't work.
Also: I wasn't aware of not using sudo on OSX. I rarely use the terminal on the work I do on this machine. Why is that?

Here's the log without using sudo. npm literally suggests using sudo or am I mistaken?

```
MacBook:~ max$ npm install --global alfred-emoj
npm ERR! tar.unpack untar error /Users/max/.npm/alfred-emoj/0.2.0/package.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "alfred-emoj"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! path /usr/local/lib/node_modules/alfred-emoj
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/alfred-emoj'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/alfred-emoj']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/alfred-emoj',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/alfred-emoj',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 

npm ERR! Please try running this command again as root/Administrator.


npm ERR! Please include the following file with any support request:
npm ERR!     /Users/max/npm-debug.log
```

**Comment by SamVerschueren** [comment]
Here you go :)  https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by SamVerschueren** [comment]
And also https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by xhain** [comment]
Awesome! This did the job.
Thank you for your time. I learned a lot about the way permissions and sudo works on OSX.

**Comment by SamVerschueren** [comment]
Glad this resolved it :)!

**Comment by sindresorhus** [comment]
@SamVerschueren Maybe we should add [`sudo-block`](https://github.com/sindresorhus/sudo-block) to alfred-link?

**Comment by SamVerschueren** [comment]
Good point! I will add it.
