### ISSUE TITLE
    TypeError: binary is not a function

### ISSUE THREAD

**Issue by joech4n** [sindresorhus/alfred-emoj#9]
Hi, I'm getting the following error when activating the workflow. Any ideas what's causing it?

    ```
    TypeError: binary is not a function
        at ClientRequest.<anonymous> (/usr/local/lib/node_modules/alfred-emoj/node_modules/got/index.js:44:62)
    ```
    
    -
    Emoj 0.2.0
    Alfred 3.1.1
    darwin x64 14.5.0

**Comment by sindresorhus** [comment]
I would guess you're on an outdated Node.js version. Try upgrading to the latest.

**Comment by joech4n** [comment]
Thad did it! Upgrading from:

```
 ❯ node --version                                                                                                              [08:07:18]
v5.5.0
```

to:

```
 ❯ node --version                                                                                                              [08:22:49]
v7.0.0
```

fixed it. Thank you!

**Comment by SamVerschueren** [comment]
Strange, it should work for Node 4+.

**Comment by pakair** [comment]
5 Jun 07:57:30 - [info] Node-RED version: v0.18.7
5 Jun 07:57:30 - [info] Node.js  version: v4.2.6
5 Jun 07:57:30 - [info] Linux 4.13.0-43-generic x64 LE
...
5 Jun 07:57:31 - [info] Starting flows
5 Jun 07:57:31 - [info] Started flows
5 Jun 07:57:36 - [red] Uncaught Exception:
5 Jun 07:57:36 - TypeError: binary is not a function
    at Function.from (native)
    at Function.from (native)
    at /usr/local/lib/node_modules/node-red/nodes/core/core/75-exec.js:135:46
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

I get similar error, what can I do? thanks.
